### PR TITLE
Simplify Luaunpack and fix bugs

### LINKED ISSUE #2: Use lua_Integer when dealing with integers coming from Lua
Instead of using int, use lua_Integer when dealing with integers coming from Lua

### LINKED ISSUE #3: Don't call luaL_error
When a user attempts to access out of bounds memory simply return nil, there's no need to call luaL_error. When the function returns, the user will see he did something naughty.

### LINKED ISSUE #4: The NULL userdata scenario is not being handled
If the user pushes values to the stack incorrectly before calling a Luaunpack function, when lua_touserdata is called the return value will be NULL.

### LINKED ISSUE #5: Remove offset field from the userdata
The userdata's offset field is being initialized but isn't used. It would be wise to remove it

### PR DESCRIPTION
**Pull request by VictorNogueiraRio**
Bugs fixed: 
- Panic in `unpackint` and `unpackstring` when the userdata isn't in the correct stack index

Corrections: 
- Use lua_Integer when dealing with integers coming from Lua
- Don't raise error in Lua when a user tries to access out of bounds memory, just return 0
- Remove unnecessary offset field from Luaunpack's userdata

Closes #2 
Closes #3 
Closes #4 
Closes #5

### CODE REVIEW

**Comment by endersonmaia** [comment]
@VictorNogueiraRio the commit messages references issues that are not in this repository, and also the branch name

maybe it's not needed or desired

File: luaunpack.c [hunk 1]
```diff
@@ -2,58 +2,60 @@
...
+	if(*offset + *size > packet->length)
 		return NULL;
 
 	return packet;
 }
 
 static int unpackint(lua_State *L) {
-	unsigned int offset;
-	unsigned int size;
+	lua_Integer offset;
```
Comment (mpolitzer) [inline luaunpack.c:32]: I would go with something like this, or event inline `verify_mem_access` completely here and in `unpackstring`.
As for the name, something like: `packet_may_access`, `access_is_bounded` or something of the sort.

```
static bool packet_may_access(packet_t *packet, lua_Integer offset, lua_Integer size)
{
	return offset + size <= packet->length;
}

static int unpackint(lua_State *L) {
	packet_t *packet = lua_touserdata(L, 1);
	lua_Integer offset = lua_tointeger(L, 2);
	lua_Integer size = lua_tointeger(L, 3);

	if (!packet || !packet_may_access(packet, offset, size))
		return 0;

	...
}
```

Comment (VictorNogueiraRio) [reply luaunpack.c:32]: I like your suggestion, but, since this PR is quite urgent, I'll keep this one as is and apply it on the next one.

Comment (mpolitzer) [reply luaunpack.c:32]: ack

**Review by mpolitzer — APPROVED** [review]

**Review by marcelstanley — APPROVED** [review]
